"""Dataclasses storing configuration for the builder UI.

This module centralises adjustable parameters for newly created particles,
springs and global environment settings. Tools and the main builder
application update these structures instead of scattering individual
attributes around the codebase.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import pygame


@dataclass
class ParticleParams:
    """Parameters applied to particles created through the builder.

    Attributes
    ----------
    mass:
        Mass assigned to new particles.
    radius:
        Rendering and collision radius for new particles.
    color:
        RGB colour tuple used when spawning particles.
    """

    mass: float = 1.0
    radius: int = 10
    color: tuple[int, int, int] = (255, 0, 0)


@dataclass
class SpringParams:
    """Configuration for springs generated by the builder."""

    stiffness: float = 200.0


@dataclass
class EnvironmentParams:
    """Global simulation values exposed in the environment tool.

    Attributes
    ----------
    gravity:
        Constant acceleration vector applied to all particles.
    repulsion_radius:
        Distance within which particles repel each other.
    repulsion_strength:
        Magnitude of the short range repulsive force.
    temperature:
        Brownian motion intensity.
    damping:
        Coefficient for viscous damping.
    """

    gravity: pygame.Vector2 = field(default_factory=lambda: pygame.Vector2(0, 0))
    repulsion_radius: float = 30.0
    repulsion_strength: float = 1000.0
    temperature: float = 0.0
    damping: float = 1.0


__all__ = ["ParticleParams", "SpringParams", "EnvironmentParams"]
