"""Dataclasses storing configuration for the builder UI.

This module centralises adjustable parameters for newly created particles,
springs and global environment settings. Tools and the main builder
application update these structures instead of scattering individual
attributes around the codebase.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import pygame


@dataclass
class ParticleParams:
    """Parameters applied to particles created through the builder.

    Attributes
    ----------
    mass:
        Mass assigned to new particles.
    radius:
        Rendering and collision radius for new particles.
    color:
        RGB colour tuple used when spawning particles.
    elasticity:
        Collision restitution factor for new particles (0–1).
    """

    mass: float = 1.0
    radius: int = 10
    color: tuple[int, int, int] = (255, 0, 0)
    elasticity: float = 1.0


@dataclass
class SpringParams:
    """Configuration for springs generated by the builder."""

    stiffness: float = 200.0


@dataclass
class VariableSpringParams:
    """Parameters for variable springs with two rest lengths.

    Attributes
    ----------
    stiffness:
        Hooke's law stiffness for the spring.
    alt_factor:
        Multiplier applied to the initial rest length to obtain the alternate
        rest length.
    speed:
        Rate in pixels per second at which the spring transitions between the
        two rest lengths.
    key:
        Keyboard key activating the alternate length. ``None`` disables key
        control.
    mode:
        ``"hold"`` requires the key to be held, while ``"toggle"`` switches
        state on each press.
    """

    stiffness: float = 200.0
    alt_factor: float = 2.0
    speed: float = 240.0
    key: int | None = pygame.K_v
    mode: str = "hold"


@dataclass
class VariableParticleParams:
    """Parameters for creating :class:`variable_particle.VariableParticle`.

    Attributes
    ----------
    alt_drag:
        Drag multiplier applied when the particle is activated.
    speed:
        Rate at which the drag moves toward the target value.
    key:
        Keyboard key controlling the particle. ``None`` disables control.
    mode:
        ``"hold"`` requires the key to be held, while ``"toggle"`` switches
        state on each press.
    """

    alt_drag: float = 100.0
    speed: float = 240.0
    key: int | None = pygame.K_g
    mode: str = "hold"


@dataclass
class EnvironmentParams:
    """Global simulation values exposed in the environment tool.

    Attributes
    ----------
    gravity:
        Constant acceleration vector applied to all particles.
    repulsion_radius:
        Distance within which particles repel each other.
    repulsion_strength:
        Magnitude of the short range repulsive force.
    temperature:
        Brownian motion intensity.
    damping:
        Coefficient for viscous damping.
    collisions:
        Toggle for particle-particle collision handling.
    collision_bucket_size:
        Spatial-hash cell size for collisions; ``0`` chooses an automatic value.
    trails_enabled:
        When ``True`` particles record their positions for rendering.
    trail_length:
        Maximum number of positions kept in each particle's trail.
    """

    gravity: pygame.Vector2 = field(default_factory=lambda: pygame.Vector2(0, 0))
    repulsion_radius: float = 30.0
    repulsion_strength: float = 1000.0
    temperature: float = 0.0
    damping: float = 1.0
    collisions: bool = True
    collision_bucket_size: float = 0.0
    trails_enabled: bool = False
    trail_length: int = 40


@dataclass
class SensorParams:
    """Parameters for sensors created in the builder.

    Attributes
    ----------
    mass:
        Mass assigned to newly created sensors.
    particle_radius:
        Rendering and collision radius for the sensor particle.
    color:
        RGB colour used when spawning sensors. Defaults to yellow.
    elasticity:
        Collision restitution factor for new sensors (0–1).
    sense_radius:
        Detection radius in world units.
    half_angle_deg:
        Half of the field of view in degrees. ``180`` covers a full circle.
    direction_deg:
        Direction the sensor faces in degrees.
    """

    mass: float = 1.0
    particle_radius: int = 10
    color: tuple[int, int, int] = (255, 255, 0)
    elasticity: float = 1.0
    sense_radius: float = 50.0
    half_angle_deg: float = 180.0
    direction_deg: float = 0.0


@dataclass
class VariableBendParams:
    """Parameters for variable bending springs.

    Attributes
    ----------
    alt_angle:
        Alternate angle in degrees used when creating new variable bends.
    speed:
        Rate in degrees per second at which the bend approaches the target
        angle.
    key:
        Keyboard key activating the alternate angle. ``None`` disables key
        control.
    mode:
        ``"hold"`` requires the key to be held, while ``"toggle"`` switches
        state on each press.
    """

    alt_angle: float = 45.0
    speed: float = 240.0
    key: int | None = pygame.K_b
    mode: str = "hold"


__all__ = [
    "ParticleParams",
    "SpringParams",
    "VariableSpringParams",
    "VariableParticleParams",
    "EnvironmentParams",
    "VariableBendParams",
    "SensorParams",
]
